version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"           #http port
      - "443:443"         #https port
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/:/etc/nginx/conf.d
      - ./cert/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-docker-network


networks:
  nginx-docker-network:
    driver: bridge
    name: nginx-docker-network
    external: true
