version: '3.7'

services:
  demo2:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo2:latest
    container_name:  demo2
    restart: always
    ports:
      - 49161:8080
    networks:
      - nginx-docker-network


networks:
  nginx-docker-network:
    driver: bridge
    name: nginx-docker-network
    external: true
